INCLUDEHEADER 	= 	-I../

all:
	g++ -std=c++11 $(INCLUDEHEADER) serial.cpp spitFire.cpp test.cpp leitorSpitFire.cpp -o testSpitfire 

wsl:
	g++ -std=c++11 $(INCLUDEHEADER) -DBUILDING_WSL serial.cpp spitFire.cpp test.cpp -o /home/suporte/testSpitfire 
